pub const Param = struct {
    name: []const u8,
    typ:  []const u8,
};

pub const ApiEntry = struct {
    name:   []const u8,
    desc:   []const u8,
    params: []const Param,
    ret:    []const u8,
};

pub const Constant = struct {
    name: []const u8,
    desc: []const u8,
};

pub const constants = [_]Constant{
    .{ .name = "MOD_SUPER", .desc = "Mod4 (Super/Win key)" },
    .{ .name = "MOD_ALT",   .desc = "Mod1 (Alt key)" },
    .{ .name = "MOD_SHIFT", .desc = "Shift modifier" },
    .{ .name = "MOD_CTRL",  .desc = "Control modifier" },
};

pub const entries = [_]ApiEntry{
    .{
        .name   = "bind",
        .desc   = "Register a keybinding.",
        .params = &.{
            .{ .name = "mod", .typ = "integer" },
            .{ .name = "key", .typ = "string" },
            .{ .name = "fn",  .typ = "function" },
        },
        .ret = "nil",
    },
    .{
        .name   = "spawn",
        .desc   = "Spawn a subprocess.",
        .params = &.{ .{ .name = "argv", .typ = "string[]" } },
        .ret    = "nil",
    },
    .{
        .name   = "focus_left",
        .desc   = "Move focus to the window on the left.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "focus_right",
        .desc   = "Move focus to the window on the right.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "focus_up",
        .desc   = "Move focus to the window above.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "focus_down",
        .desc   = "Move focus to the window below.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "exec_once",
        .desc   = "Execute a command at startup only",
        .params = &.{ .{ .name = "argv", .typ = "string[]" } },
        .ret    = "nil",
    },
    .{
        .name   = "focus",
        .desc   = "Focus a specific node by ID.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "exchange_left",
        .desc   = "Swap focused window with the one to its left.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "exchange_right",
        .desc   = "Swap focused window with the one to its right.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "exchange_up",
        .desc   = "Swap focused window with the one above.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "exchange_down",
        .desc   = "Swap focused window with the one below.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name = "set_default_arranger",
        .desc = "Set the default layout function for new workspaces.",
        .params = &.{ .{ .name = "fn", .typ = "function" } },
        .ret  = "nil",
    },
    .{
        .name   = "register_arranger",
        .desc   = "Register a new layout function to a workspace.",
        .params = &.{ .{ .name = "workspace_id", .typ = "integer" }, .{ .name = "fn", .typ = "function" } },
        .ret    = "nil",
    },
    .{
        .name   = "get_focused",
        .desc   = "Return the ID of the currently focused node, or nil.",
        .params = &.{},
        .ret    = "integer|nil",
    },
    .{
        .name   = "kill_client",
        .desc   = "Send WM_DELETE_WINDOW to the focused client.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "remove_node",
        .desc   = "Remove a node from the graph entirely.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "get_node_type",
        .desc   = "Return 'window', 'empty', 'workspace', or nil.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "'window'|'empty'|'workspace'|nil",
    },
    .{
        .name   = "get_node_geometry",
        .desc   = "Return {x, y, width, height} for a node, or nil if not found.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "{ x: integer, y: integer, width: integer, height: integer }|nil",
    },
    .{
        .name   = "get_node_info",
        .desc   = "Return geometry table for a node.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "{ x: integer, y: integer, width: integer, height: integer }",
    },
    .{
        .name   = "create_container",
        .desc   = "Create an empty container node in the current graph.",
        .params = &.{},
        .ret    = "integer",
    },
    .{
        .name   = "destroy_container",
        .desc   = "Remove an empty container node from the graph.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "create_root_node",
        .desc   = "Create a full-screen empty container.",
        .params = &.{},
        .ret    = "integer",
    },
    .{
        .name   = "create_empty_node",
        .desc   = "Create an unconstrained empty node.",
        .params = &.{},
        .ret    = "integer",
    },
    .{
        .name   = "clear_constraints",
        .desc   = "Remove all constraints from a node.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "grid_cell",
        .desc   = "Place node in a grid cell of container. col/row are 0-based.",
        .params = &.{
            .{ .name = "id",        .typ = "integer" },
            .{ .name = "col",       .typ = "integer" },
            .{ .name = "row",       .typ = "integer" },
            .{ .name = "cols",      .typ = "integer" },
            .{ .name = "rows",      .typ = "integer" },
            .{ .name = "container", .typ = "integer" },
        },
        .ret = "nil",
    },
    .{
        .name   = "grid_cell_abs",
        .desc   = "Place node in a grid cell of container, with absolute pixel sizes.",
        .params = &.{
            .{ .name = "id",        .typ = "integer" },
            .{ .name = "x",         .typ = "integer" },
            .{ .name = "y",         .typ = "integer" },
            .{ .name = "w",         .typ = "integer" },
            .{ .name = "h",         .typ = "integer" },
            .{ .name = "container", .typ = "integer" },
        },
        .ret = "nil",
    },
    .{
        .name   = "left_of",
        .desc   = "Constrain: a.right == b.left.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "right_of",
        .desc   = "Constrain: a.left == b.right.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "above",
        .desc   = "Constrain: a.bottom == b.top.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "below",
        .desc   = "Constrain: a.top == b.bottom.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "align_left",
        .desc   = "Constrain: a.x == b.x.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "align_top",
        .desc   = "Constrain: a.y == b.y.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "align_right",
        .desc   = "Constrain: a.right == b.right.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "align_bottom",
        .desc   = "Constrain: a.bottom == b.bottom.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "equal_width",
        .desc   = "Constrain: a.width == b.width.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "equal_height",
        .desc   = "Constrain: a.height == b.height.",
        .params = &.{ .{ .name = "a", .typ = "integer" }, .{ .name = "b", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "fixed_ratio",
        .desc   = "Constrain: width/height == ratio.",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "ratio", .typ = "number" } },
        .ret    = "nil",
    },
    .{
        .name   = "fixed_width",
        .desc   = "Constrain: width == w.",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "w", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "fixed_height",
        .desc   = "Constrain: height == h.",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "h", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "fixed_x",
        .desc   = "Constrain: x == x.",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "x", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "fixed_y",
        .desc   = "Constrain: y == y.",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "y", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "reparent",
        .desc   = "Make child fill parent via a 1x1 grid_cell constraint.",
        .params = &.{ .{ .name = "child", .typ = "integer" }, .{ .name = "parent", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "get_container_of",
        .desc   = "Return the container ID that node is grid_cell'd into, or nil.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "integer|nil",
    },
    .{
        .name   = "get_all_windows",
        .desc   = "Return list of all window/workspace node IDs in current graph.",
        .params = &.{},
        .ret    = "integer[]",
    },
    .{
        .name   = "screen_width",
        .desc   = "Return screen width in pixels.",
        .params = &.{},
        .ret    = "integer",
    },
    .{
        .name   = "screen_height",
        .desc   = "Return screen height in pixels.",
        .params = &.{},
        .ret    = "integer",
    },
    .{
        .name   = "set_node_empty",
        .desc   = "Clear a node's window content.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_node_window",
        .desc   = "Assign an X window to a node.",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "win", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "move_window_to_node",
        .desc   = "Move the window from src node to dst node.",
        .params = &.{ .{ .name = "src", .typ = "integer" }, .{ .name = "dst", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_resize_modifier",
        .desc   = "Set the modifier key used for mouse resize.",
        .params = &.{ .{ .name = "mod", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "resize_edge",
        .desc   = "Move an edge of a specific node by delta pixels.",
        .params = &.{
            .{ .name = "id",    .typ = "integer" },
            .{ .name = "dir",   .typ = "'left'|'right'|'up'|'down'" },
            .{ .name = "delta", .typ = "integer" },
        },
        .ret = "nil",
    },
    .{
        .name   = "resize_corner",
        .desc   = "Move a corner of a specific node.",
        .params = &.{
            .{ .name = "id",      .typ = "integer" },
            .{ .name = "delta_x", .typ = "integer" },
            .{ .name = "delta_y", .typ = "integer" },
        },
        .ret = "nil",
    },
    .{
        .name   = "resize_focused_edge",
        .desc   = "Move an edge of the focused node by delta pixels.",
        .params = &.{
            .{ .name = "dir",   .typ = "'left'|'right'|'up'|'down'" },
            .{ .name = "delta", .typ = "integer" },
        },
        .ret = "nil",
    },
    .{
        .name   = "resize_focused_corner",
        .desc   = "Move a corner of the focused node.",
        .params = &.{
            .{ .name = "delta_x", .typ = "integer" },
            .{ .name = "delta_y", .typ = "integer" },
        },
        .ret = "nil",
    },
    .{
        .name   = "set_float_modifier",
        .desc   = "Set the modifier key used for floating window drag.",
        .params = &.{ .{ .name = "mod", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "toggle_floating",
        .desc   = "Toggle floating mode on the focused window.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "set_node_focused_border_color",
        .desc   = "Set focused border color for a specific node (0xRRGGBB).",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "color", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_node_unfocused_border_color",
        .desc   = "Set unfocused border color for a specific node (0xRRGGBB).",
        .params = &.{ .{ .name = "id", .typ = "integer" }, .{ .name = "color", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_default_focus_border_color",
        .desc   = "Set default focused border color (0xRRGGBB).",
        .params = &.{ .{ .name = "color", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_default_unfocused_border_color",
        .desc   = "Set default unfocused border color (0xRRGGBB).",
        .params = &.{ .{ .name = "color", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_border_width",
        .desc   = "Set window border width in pixels.",
        .params = &.{ .{ .name = "width", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "create_nested_workspace",
        .desc   = "Create a new nested workspace node in the current graph.",
        .params = &.{},
        .ret    = "integer",
    },
    .{
        .name   = "enter_nested",
        .desc   = "Enter the focused workspace node.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "leave_nested",
        .desc   = "Leave the current nested workspace.",
        .params = &.{},
        .ret    = "nil",
    },
    .{
        .name   = "switch_workspace",
        .desc   = "Enter a workspace node by ID.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "send_to_workspace",
        .desc   = "Move the focused window to a workspace node by ID.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "get_workspace",
        .desc   = "Return the nth workspace node ID (1-based) in the current graph.",
        .params = &.{ .{ .name = "index", .typ = "integer" } },
        .ret    = "integer|nil",
    },
    .{
        .name   = "get_workspaces_at_level",
        .desc   = "Return list of workspace node IDs at the current nesting level.",
        .params = &.{},
        .ret    = "integer[]",
    },
    .{
        .name   = "enter_workspace_by_id",
        .desc   = "Enter a workspace node by its ID.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "switch_to_workspace",
        .desc   = "Switch to workspace by 1-based index, creating it if needed.",
        .params = &.{ .{ .name = "index", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "set_on_remove_promote",
        .desc   = "Set on_remove=promote: when removed, sibling is promoted into its slot.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "unregister_node",
        .desc   = "Remove a node from the registry without freeing it.",
        .params = &.{ .{ .name = "id", .typ = "integer" } },
        .ret    = "nil",
    },
    .{
        .name   = "get_cursor_pos",
        .desc   = "Return cursor position as (x, y) in screen coordinates.",
        .params = &.{},
        .ret    = "integer, integer",
    },
    .{
        .name   = "get_cursor_relative_to_focused",
        .desc   = "Return cursor offset from focused window center as (dx, dy).",
        .params = &.{},
        .ret    = "integer, integer",
    },
};
